SELECT
    P.*
FROM
    "PREGUNTA" P
JOIN
    "EXAMEN_PREGUNTA" EP ON P."ID_PREGUNTA" = EP."ID_PREGUNTA"
WHERE
    EP."ID_EXAMEN" = 1;

/

SELECT
    H.*,
    GH."ID_GRUPO"
FROM
    "HORARIO" H
LEFT JOIN
    "GRUPO_HORARIO" GH ON H."ID_HORARIO" = GH."ID_HORARIO";

/

SELECT
    E.*
FROM
    "ESTUDIANTE" E
JOIN
    "ESTUDIANTE_GRUPO" EG ON E."ID_ESTUDIANTE" = EG."ID_ESTUDIANTE"
WHERE
    EG."ID_GRUPO" = 1;

/

SELECT
    E.*,
    H."DIA",
    H."HORA",
    GH."ID_GRUPO"
FROM
    "ESTUDIANTE" E
JOIN
    "ESTUDIANTE_GRUPO" EG ON E."ID_ESTUDIANTE" = EG."ID_ESTUDIANTE"
JOIN
    "GRUPO_HORARIO" GH ON EG."ID_GRUPO" = GH."ID_GRUPO"
JOIN
    "HORARIO" H ON GH."ID_HORARIO" = H."ID_HORARIO";
