--PROCEDIMIENTO PARA INSERTAR IN DATO EN LA TABLA REGISTRO PARA CUANDO SE ELIMINE UN ESTUDIANTE

CREATE OR REPLACE PROCEDURE GUARDAR_REGISTRO_AUD_ESTUDIANTE
AS 
BEGIN 
    -- Se inserta registros en la tabla REGISTRO 
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('ESTUDIANTE', 'DELETE', SYSDATE());
END;
/
--PROCEDIMIENTO PARA INSERTAR IN DATO EN LA TABLA REGISTRO PARA CUANDO SE ELIMINE UN PROFESOR

CREATE OR REPLACE PROCEDURE GUARDAR_REGISTRO_AUD_PROFESOR
AS 
BEGIN 
    -- Se inserta registros en la tabla REGISTRO 
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PROFESOR', 'DELETE', SYSDATE());
END;