-- Se crea role de estudiante y se asignan privilegios en la BD
CREATE ROLE ESTUDIANTE;
GRANT CREATE SESSION TO ESTUDIANTE;
GRANT SELECT, INSERT, UPDATE ON EXAMEN TO ESTUDIANTE;
GRANT SELECT ON PRESENTACION_EXAMEN TO ESTUDIANTE;
GRANT SELECT ON CURSO TO ESTUDIANTE;
GRANT SELECT ON GRUPO TO ESTUDIANTE;
GRANT SELECT ON HORARIO TO ESTUDIANTE;


-- Se crea role de profesor y se asignan privilegios en la BD
CREATE ROLE PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ESTUDIANTE TO PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXAMEN TO PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON PREGUNTA TO PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRESENTACION_EXAMEN TO PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HORARIO TO PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON GRUPO TO PROFESOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ESTUDIANTE_GRUPO TO PROFESOR;
GRANT CREATE SESSION TO PROFESOR;

-- USUARIOS BD

CREATE USER PROFESOR_ IDENTIFIED BY "123456";
CREATE USER ESTUDIANTE_ IDENTIFIED BY "123456";

GRANT PROFESOR TO PROFESOR_;
GRANT ESTUDIANTE TO ESTUDIANTE_;




