SELECT P.ID_PREGUNTA, P.TEXTO, P.OPCIONES, P.RESPUESTAS_CORRECTAS, P.ID_TIPO, P.TEMA,
       CASE
           WHEN P.PRIVACIDAD = 0 THEN 'PUBLICA'
           WHEN P.PRIVACIDAD = 1 THEN 'PRIVADA'
           ELSE 'DESCONOCIDA'
       END AS PRIVACIDAD
FROM PREGUNTA P
INNER JOIN EXAMEN_PREGUNTA EP ON P.ID_PREGUNTA = EP.ID_PREGUNTA
INNER JOIN EXAMEN E ON EP.ID_EXAMEN = E.ID_EXAMEN
WHERE (P.TEMA = 'No definido' AND P.PRIVACIDAD = 0)
   OR (P.TEMA = 'No definido' AND E.ID_PROFESOR = 2 )
ORDER BY P.TEXTO;

/

