-- Trigger para insertar acciones realizadas en estudiantes en la tabla REGISTRO
CREATE OR REPLACE TRIGGER TR_INSERT_ESTUDIANTES
AFTER INSERT ON ESTUDIANTE
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('ESTUDIANTE', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_ESTUDIANTES
AFTER UPDATE ON ESTUDIANTE
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('ESTUDIANTE', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en PROFESOR en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_PROFESOR
AFTER INSERT ON PROFESOR
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PROFESOR', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_PROFESOR
AFTER UPDATE ON PROFESOR
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PROFESOR', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en CONTENIDO_DE_UNIDAD en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_CONTENIDO_DE_UNIDAD
AFTER INSERT ON CONTENIDO_DE_UNIDAD
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('CONTENIDO_DE_UNIDAD', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_CONTENIDO_DE_UNIDAD
AFTER UPDATE ON CONTENIDO_DE_UNIDAD
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('CONTENIDO_DE_UNIDAD', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en CURSO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_CURSO
AFTER INSERT ON CURSO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('CURSO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_CURSO
AFTER UPDATE ON CURSO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('CURSO', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en ESTUDIANTE_GRUPO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_ESTUDIANTE_GRUPO
AFTER INSERT ON ESTUDIANTE_GRUPO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('ESTUDIANTE_GRUPO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_ESTUDIANTE_GRUPO
AFTER UPDATE ON ESTUDIANTE_GRUPO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('ESTUDIANTE_GRUPO', 'UPDATE', SYSDATE());
END;
/

-- Trigger para insertar acciones realizadas en EXAMEN en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_EXAMEN
AFTER INSERT ON EXAMEN
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('EXAMEN', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_EXAMEN
AFTER UPDATE ON EXAMEN
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('EXAMEN', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en EXAMEN_HORARIO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_EXAMEN_HORARIO
AFTER INSERT ON EXAMEN_HORARIO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('EXAMEN_HORARIO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_EXAMEN_HORARIO
AFTER UPDATE ON EXAMEN_HORARIO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('EXAMEN_HORARIO', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en EXAMEN_PREGUNTA en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_EXAMEN_PREGUNTA
AFTER INSERT ON EXAMEN_PREGUNTA
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('EXAMEN_PREGUNTA', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_EXAMEN_PREGUNTA
AFTER UPDATE ON EXAMEN_PREGUNTA
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('EXAMEN_PREGUNTA', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en EXAMEN_HORARIO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_GRUPO
AFTER INSERT ON GRUPO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('GRUPO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_GRUPO
AFTER UPDATE ON GRUPO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('GRUPO', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en GRUPO_HORARIO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_GRUPO_HORARIO
AFTER INSERT ON GRUPO_HORARIO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('GRUPO_HORARIO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_GRUPO_HORARIO
AFTER UPDATE ON GRUPO_HORARIO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('GRUPO_HORARIO', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en HORARIO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_HORARIO
AFTER INSERT ON HORARIO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('HORARIO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_HORARIO
AFTER UPDATE ON HORARIO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('HORARIO', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en PREGUNTA en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_PREGUNTA
AFTER INSERT ON PREGUNTA
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PREGUNTA', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_PREGUNTA
AFTER UPDATE ON PREGUNTA
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PREGUNTA', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en PRESENTACION_EXAMEN en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_PRESENTACION_EXAMEN
AFTER INSERT ON PRESENTACION_EXAMEN
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PRESENTACION_EXAMEN', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_PRESENTACION_EXAMEN
AFTER UPDATE ON PRESENTACION_EXAMEN
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('PRESENTACION_EXAMEN', 'UPDATE', SYSDATE());
END;
/
-- Trigger para insertar acciones realizadas en UNIDAD_DE_CURSO en la tabla REGISTRO

CREATE OR REPLACE TRIGGER TR_INSERT_UNIDAD_DE_CURSO
AFTER INSERT ON UNIDAD_DE_CURSO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('UNIDAD_DE_CURSO', 'INSERT', SYSDATE());
END;
/
CREATE OR REPLACE TRIGGER TR_UPDATE_UNIDAD_DE_CURSO
AFTER UPDATE ON UNIDAD_DE_CURSO
BEGIN
    INSERT INTO REGISTRO (TABLA_ACTUALIZADA, ACCION_REALIZADA, FECHA_ACTUALIZACION)
    VALUES('UNIDAD_DE_CURSO', 'UPDATE', SYSDATE());
END;
/